### PR TITLE
Support any label matching pattern do-not-merge/*

### PR DESCRIPTION
**Pull request by dhiller**
Adds support for labels matching patterns containing stars, use case is matching of any label starting with `work-in-progress/`

### CODE REVIEW

**Comment by dhiller** [comment]
@fgimenez this one is ready for review :)

**Review by fgimenez — COMMENTED** [review]
Awesome work thanks a lot!! Could you please update the readme with the new criteria for a PR being considered as part of the merge queue? Mentioning the do -not-merge pattern there should be enough.

**Comment by dhiller** [comment]
@fgimenez covered your feedback, PTAL, thanks!

**Review by fgimenez — APPROVED** [review]
Thank you!!

**Pull request merged**
